#!/usr/bin/env bash

echo "Swift CodeCov Integration";

# Determine OS
UNAME=`uname`;
if [[ $UNAME == "Darwin" ]];
then
    OS="macos";
else
    echo "🚫  Unsupported OS: $UNAME, skipping...";
    exit 0;
fi
echo "🖥  Operating System: $OS";


PROJECT_OUTPUT=`swift package generate-xcodeproj --enable-code-coverage`;
PROJECT_NAME="${PROJECT_OUTPUT/generated: .\//}"
SCHEME_NAME=$(xcodebuild -list -project $PROJECT_NAME | grep --after-context=1 '^\s*Schemes:' | tail -n 1 | xargs)

echo "🚀  Testing: $SCHEME_NAME";

WORKING_DIRECTORY=$(PWD) xcodebuild -project $PROJECT_NAME -scheme $SCHEME_NAME -sdk macosx -destination arch=x86_64 -configuration Debug test
bash <(curl -s https://codecov.io/bash)

echo "✅  Done";
